name: CI/CD MLflow
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CSV_URL: "dataset_processing.csv"
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
 
      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
 
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL  
 
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dagshub
          pip install mlflow
          pip install mlflow_skinny
          pip install numpy
          pip install pandas
          pip install scikit_learn
          pip install xgboost

      # Run as a mlflow project
      - name: Run mlflow project
        working-directory: MLproject
        run: 
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        working-directory: MLproject
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # GET MODEL_ID
      - name: Get Model ID
        id: get_model_id
        run: |
          MODEL_ID=$(ls MLproject/mlruns/0/models | head -1)
          echo "model_id=$MODEL_ID" >> $GITHUB_ENV
          echo "Model ID: $MODEL_ID"

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Build Docker Model
      #   working-directory: MLproject
      #   run: |
      #     mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc"

      # Build Docker Image from Model
      - name: Build Docker Image from MLflow Model
        run: |
          mlflow models build-docker \
            -m "MLproject/mlruns/0/models/$MODEL_ID/artifacts" \
            -n "${{ secrets.DOCKER_HUB_USERNAME }}/classification:latest"
      
      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/classification:latest

      # Save models to GitHub Repository
      - name: Save mlruns to repo
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git add .
          git commit -m "AUTOMATICALLY run mlflow project"
          git push origin master
